---
# Implement your Workload removal tasks here

- set_fact:
    ansible_python_interpreter: "/opt/virtualenvs/k8s/bin/python"

- name: Ensure there is connectivity to OCP cluster as system:admin
  command: oc whoami
  register: whoami
  changed_when: false

- name: Fail if not system:admin
  fail:
    msg: "Not connected to OCP as system:admin"
  when: whoami.stdout != "system:admin"

# 1. Quay and Noobaa
- name: Remove ArgoCD's Quay app
  k8s:
    state: absent
    definition: "{{ lookup('file', './files/quay/deploy-quay.yaml') }}"

- name: Remove Quay instance
  k8s:
    state: absent
    definition: "{{ lookup('file', './files/quay/deploy/quay-registry.yaml') }}"    

- name: Remove Noobaa instance
  k8s:
    state: absent
    definition: "{{ lookup('file', './files/quay/noobaa/noobaa.yaml') }}"      

- name: Wait until no rcm controller is running before removing the subscriptions
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: openshift-operators
    name: quay-registry-quay-app
  register: rcm_controller_deployment
  retries: 30
  delay: 20
  until: rcm_controller_deployment.resources | length == 0

- name: Wait until no rcm controller is running before removing the subscriptions
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: openshift-operators
    name: noobaa-endpoint
  register: rcm_controller_deployment
  retries: 30
  delay: 20
  until: rcm_controller_deployment.resources | length == 0

- name: Ensure Quay Subscription is absent
  k8s:
    state: absent
    definition: "{{ lookup('file', './files/quay/operators/quay-sub.yaml') }}"

- name: Ensure Quay CSV is absent
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: quay-operator.v3.6.1
    namespace: openshift-operators

- name: Ensure openshift-storage Subscription is absent
  k8s:
    state: absent
    definition: "{{ lookup('file', './files/quay/operators/odf-sub.yaml') }}"    

- name: Ensure openshift-storage OperatorGroup is absent
  k8s:
    state: absent
    definition: "{{ lookup('file', './files/quay/operators/odf-og.yaml') }}"

- name: Ensure openshift-storage CSV is absent
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: ocs-operator.v4.8.4
    namespace: openshift-storage

- name: Ensure openshift-storage Namespace is absent
  k8s:
    name: openshift-storage
    api_version: v1
    kind: Namespace
    state: absent

# 2. ACM
- name: Remove Argocd's ACM app
  k8s:
    state: absent
    definition: "{{ lookup('file', './files/acm/deploy-acm.yaml') }}"

- name: Ensure ACM multiclusterhub is absent
  k8s:
    state: absent
    definition: "{{ lookup('file', './files/acm/mch/acm-mch.yaml') }}"

- name: Wait until no ocm controller is running before removing the subscriptions
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: open-cluster-management
    name: ocm-controller
  register: rcm_controller_deployment
  retries: 30
  delay: 20
  until: rcm_controller_deployment.resources | length == 0

- name: Ensure RHACM Subscription is absent
  k8s:
    state: absent
    definition: "{{ lookup('file', './files/acm/operator/acm-sub.yaml') }}"

- name: Ensure RHACM OperatorGroup is absent
  k8s:
    state: absent
    definition: "{{ lookup('file', './files/acm/operator/acm-og.yaml') }}"

- name: Ensure ACM CSV is absent
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: advanced-cluster-management.v2.4.0
    namespace: open-cluster-management

- name: Wait until no pods are running before removing the namespace
  k8s_info:
    kind: Pod
    namespace: open-cluster-management
  register: pod_list
  retries: 30
  delay: 20
  until: pod_list.resources | length == 0

- name: Ensure RHACM Namespace is absent
  k8s:
    name: open-cluster-management
    api_version: v1
    kind: Namespace
    state: absent

# 3. ACS
- name: Remove Argocd's ACS app
  k8s:
    state: absent
    definition: "{{ lookup('file', './files/acs/deploy-acs.yaml') }}"

- name: Ensure ACS central is absent
  k8s:
    state: absent
    definition: "{{ lookup('file', './files/acs/deploy/acs-central.yaml') }}"

- name: Ensure ACS secured cluster is absent
  k8s:
    state: absent
    definition: "{{ lookup('file', './files/acs/deploy/secured-cluster.yaml') }}"    

- name: Wait until no rcm controller is running before removing the subscriptions
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: stackrox
    name: central
  register: rcm_controller_deployment
  retries: 30
  delay: 20
  until: rcm_controller_deployment.resources | length == 0

- name: Ensure ACS Subscription is absent
  k8s:
    state: absent
    definition: "{{ lookup('file', './files/acs/operator/acs-sub.yaml') }}"

- name: Ensure ACS CSV is absent
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: rhacs-operator.v3.66.1
    namespace: stackrox

- name: Wait until no pods are running before removing the namespace
  k8s_info:
    kind: Pod
    namespace: stackrox
  register: pod_list
  retries: 30
  delay: 20
  until: pod_list.resources | length == 0

- name: Ensure stackrox Namespace is absent
  k8s:
    name: stackrox
    api_version: v1
    kind: Namespace
    state: absent

- name: Delete stackrox-sample-app Namespace also
  k8s:
    name: stackrox-sample-app
    api_version: v1
    kind: Namespace
    state: absent    

# 4. ArgoCD
- name: Ensure ArgoCD instance is absent
  k8s:
    state: absent
    api_version: pipelines.openshift.io/v1alpha1
    kind: GitopsService
    name: cluster

- name: Wait until no rcm controller is running before removing the subscriptions
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: openshift-gitops
    name: cluster
  register: rcm_controller_deployment
  retries: 30
  delay: 20
  until: rcm_controller_deployment.resources | length == 0

- name: Ensure ArgoCD Subscription is absent
  k8s:
    state: absent
    definition: "{{ lookup('template', './templates/argocd/subscription.j2') }}"

- name: Ensure ArgoCD CSV is absent
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: openshift-gitops-operator.v1.3.1
    namespace: openshift-gitops

- name: Wait until no pods are running before removing the namespace
  k8s_info:
    kind: Pod
    namespace: openshift-gitops
  register: pod_list
  retries: 30
  delay: 20
  until: pod_list.resources | length == 0

- name: Ensure openshift-gitops Namespace is absent
  k8s:
    name: openshift-gitops
    api_version: v1
    kind: Namespace
    state: absent

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
