---
- name: Ensure project on ArgoCD exists
  k8s:
    state: present
    definition: "{{ lookup('file', './files/argocd-ocp-tools-project.yaml') }}"

- name: Create ArgoCD Application which deploys ACM
  k8s:
    state: present
    definition: "{{ lookup('file', './files/acm/deploy-acm.yaml') }}"